export const HTTP_DEFAULT_TIMEOUT = 30000;

export const HTTP_ERROR_NAMES = {
  ABORT: 'AbortError',
} as const;

export const HTTP_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  PATCH: 'PATCH',
  DELETE: 'DELETE',
  HEAD: 'HEAD',
  OPTIONS: 'OPTIONS',
} as const;

export const HTTP_STATUS_GROUP = {
  SUCCESS: 'SUCCESS',
  REDIRECTION: 'REDIRECTION',
  CLIENT_ERROR: 'CLIENT_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
} as const;

export const HTTP_STATUS = {
  [HTTP_STATUS_GROUP.SUCCESS]: {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
  },
  [HTTP_STATUS_GROUP.REDIRECTION]: {
    MOVED_PERMANENTLY: 301,
    FOUND: 302,
    NOT_MODIFIED: 304,
  },
  [HTTP_STATUS_GROUP.CLIENT_ERROR]: {
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    REQUEST_TIMEOUT: 408,
  },
  [HTTP_STATUS_GROUP.SERVER_ERROR]: {
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
  },
} as const;

export const HTTP_STATUS_TEXT = {
  [HTTP_STATUS_GROUP.SUCCESS]: {
    [HTTP_STATUS[HTTP_STATUS_GROUP.SUCCESS].OK]: 'OK',
    [HTTP_STATUS[HTTP_STATUS_GROUP.SUCCESS].CREATED]: 'Created',
    [HTTP_STATUS[HTTP_STATUS_GROUP.SUCCESS].ACCEPTED]: 'Accepted',
    [HTTP_STATUS[HTTP_STATUS_GROUP.SUCCESS].NO_CONTENT]: 'No Content',
  },
  [HTTP_STATUS_GROUP.REDIRECTION]: {
    [HTTP_STATUS[HTTP_STATUS_GROUP.REDIRECTION].MOVED_PERMANENTLY]:
      'Moved Permanently',
    [HTTP_STATUS[HTTP_STATUS_GROUP.REDIRECTION].FOUND]: 'Found',
    [HTTP_STATUS[HTTP_STATUS_GROUP.REDIRECTION].NOT_MODIFIED]: 'Not Modified',
  },
  [HTTP_STATUS_GROUP.CLIENT_ERROR]: {
    [HTTP_STATUS[HTTP_STATUS_GROUP.CLIENT_ERROR].BAD_REQUEST]: 'Bad Request',
    [HTTP_STATUS[HTTP_STATUS_GROUP.CLIENT_ERROR].UNAUTHORIZED]: 'Unauthorized',
    [HTTP_STATUS[HTTP_STATUS_GROUP.CLIENT_ERROR].FORBIDDEN]: 'Forbidden',
    [HTTP_STATUS[HTTP_STATUS_GROUP.CLIENT_ERROR].NOT_FOUND]: 'Not Found',
    [HTTP_STATUS[HTTP_STATUS_GROUP.CLIENT_ERROR].METHOD_NOT_ALLOWED]:
      'Method Not Allowed',
    [HTTP_STATUS[HTTP_STATUS_GROUP.CLIENT_ERROR].CONFLICT]: 'Conflict',
    [HTTP_STATUS[HTTP_STATUS_GROUP.CLIENT_ERROR].UNPROCESSABLE_ENTITY]:
      'Unprocessable Entity',
    [HTTP_STATUS[HTTP_STATUS_GROUP.CLIENT_ERROR].TOO_MANY_REQUESTS]:
      'Too Many Requests',
    [HTTP_STATUS[HTTP_STATUS_GROUP.CLIENT_ERROR].REQUEST_TIMEOUT]:
      'Request Timeout',
  },
  [HTTP_STATUS_GROUP.SERVER_ERROR]: {
    [HTTP_STATUS[HTTP_STATUS_GROUP.SERVER_ERROR].INTERNAL_SERVER_ERROR]:
      'Internal Server Error',
    [HTTP_STATUS[HTTP_STATUS_GROUP.SERVER_ERROR].NOT_IMPLEMENTED]:
      'Not Implemented',
    [HTTP_STATUS[HTTP_STATUS_GROUP.SERVER_ERROR].BAD_GATEWAY]: 'Bad Gateway',
    [HTTP_STATUS[HTTP_STATUS_GROUP.SERVER_ERROR].SERVICE_UNAVAILABLE]:
      'Service Unavailable',
    [HTTP_STATUS[HTTP_STATUS_GROUP.SERVER_ERROR].GATEWAY_TIMEOUT]:
      'Gateway Timeout',
  },
} as const;
